# permissions for end users to view directorycleaners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: directorycleaner-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: abc
    app.kubernetes.io/part-of: abc
    app.kubernetes.io/managed-by: kustomize
  name: directorycleaner-viewer-role
rules:
- apiGroups:
  - cleanup.example.com
  resources:
  - directorycleaners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cleanup.example.com
  resources:
  - directorycleaners/status
  verbs:
  - get
